const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const ProjectSchema = new Schema({
  ProjectNo: Number,
  ProjectName: String,
  CustomerNumber: Number,
  CustomerName: String,
  DepartmentID: String,
  QboxStatus: String,
  RekonnectStatus: String,
  ProjectStartDate: Date,
  ProjectEndDate: Date,
  EM: String,
  EP: String,
  SP: String,
  Error: String,
  A01: Number,
  A02: Number,
  A03: Number,
  A04: Number,
  A05: Number,
  A06: Number,
  A07: Number,
  A08: Number,
  A09: Number,
  A10: Number,
  A11: Number,
  A12: Number,
  A13: Number,
  A14: Number,
  A15: Number,
  A16: Number,
  A17: Number,
  A18: Number,
  A19: Number,
  A20: Number,
  A21: Number,
  A22: Number,
  B23: Number,
  B24: Number,
  B25: Number,
  B26: Number,
  B27: Number,
  B28: Number,
  C29: Number,
  C30: Number,
  C31: Number,
  C32: Number,
  C33: Number,
  C34: Number,
  C35: Number,
  C36: Number,
  C37: Number,
  C38: Number,
  C39: Number,
  D40: Number,
  D41: Number,
  D42: Number,
  D43: Number,
  D44: Number,
});

const ProjectDetail = mongoose.model("projectdetail", ProjectSchema);
module.exports = ProjectDetail;
